name: Test
on:
  workflow_dispatch:
  pull_request:
  
  
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo
        run: |
          echo "${{ toJson(github) }}"
          echo "head: $HEAD"
          echo "base: $BASE"
          echo "ref: $REF"
          echo "Is Manual: ${{ github.event_name == 'workflow_dispatch' }}"
          echo "Is Web: ${{ contains(env.HEAD, 'web-') }}"
          echo "Is Preview: ${{ contains(env.BASE, 'preview') }}"
          echo "Is Production: ${{ contains(env.BASE, 'production') }}"
        env:
          HEAD: ${{ github.head_ref }}
          BASE: ${{ github.base_ref }}
          REF: ${{ github.ref }}
