name: Test
on:
  workflow_dispatch:
  pull_request:
  
  
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo
        run: |
          echo "head: $HEAD"
          echo "base: $BASE"
          echo "ref: $REF"
          echo "IsWeb: ${{ contains(env.HEAD, 'web-') }}"
        env:
          HEAD: ${{ github.head_ref }}
          BASE: ${{ github.base_ref }}
          REF: ${{ github.ref }}
