name: Test
on:
  workflow_dispatch:
  pull_request:
  
  
jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - run: |
        echo "head: ${{ github.head_ref }}"
        echo "base: ${{ github.base_ref }}"
        echo "ref: ${{ github_ref }}"
