name: PR
on:
  - pull_request
  - pull_request_target
  - issues
  - issue_comment

permissions: read-all

jobs:
  pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            echo "${{ toJson(github.event) }}"
